latent_attention_masks: False
phrase_grounding_mode: False
filter_bad_impressions: False
root: $WORK
work_dir: $WORK/cxr_phrase_grounding
data_dir: $WORK/data/mimic
component_dir: $WORK/cxr_phrase_grounding/components
mask_dir: $WORK/preliminary_masks
log_dir: $WORK/cxr_phrase_grounding/log
validation_split: 0.1

dataloading:
  batch_size: 256
  num_workers: 0

datasets:
  C: 4
  H: 512
  W: 512
  f: 8

  train:
    dataset: chestxraymimic
    base_dir: $WORK/data/mimic
    precomputed_base_dir: $WORK/data/mimic
    split: mscxr
    preload: true
    shuffle: true
    save_original_images: false
    limit_dataset:
      - 0
      - 512
    dataset_csv: mimic_metadata_preprocessed.csv

  test:
    dataset: chestxraymimicbbox
    base_dir: $WORK/data/mimic
    split: mscxr
    preload: true
    save_original_images: true

sample:
  ddim_steps: 75
  iou_batch_size: 8
  n_synth_samples_per_class: 625
  seed: 4200
  latent_C: 4
  latent_H: 64
  latent_W: 64
