latent_attention_masks: False
phrase_grounding_mode: False
filter_bad_impressions: False
root: /vol/ideadata/ce90tate/
work_dir: /vol/ideadata/ce90tate/cxr_phrase_grounding
data_dir: /vol/ideadata/ce90tate/data/mimic
component_dir: /vol/ideadata/ce90tate/cxr_phrase_grounding/components
mask_dir: /vol/ideadata/ce90tate/preliminary_masks
log_dir: /vol/ideadata/ce90tate/cxr_phrase_grounding/log

dataloading:
  batch_size: 8
  num_workers: 0

datasets:
  C: 4
  H: 512
  W: 512
  f: 8

  train:
    dataset: chestxraymimic
    base_dir: /vol/ideadata/ed52egek/data/mimic/jpg/physionet.org/files/mimic-cxr-jpg/2.0.0
    precomputed_base_dir: /vol/ideadata/ce90tate/data/mimic
    split: mscxr
    preload: true
    limit_dataset:
      - 0
      - 256
    shuffle: true
    save_original_images: false
    dataset_csv: /vol/ideadata/ce90tate/data/mimic/cxr-record-list-impressions-no_p19.csv

  val:
    dataset: chestxraymimic
    base_dir: /vol/ideadata/ed52egek/data/mimic/jpg/physionet.org/files/mimic-cxr-jpg/2.0.0
    precomputed_base_dir: /vol/ideadata/ce90tate/data/mimic
    split: mscxr
    limit_dataset:
      - 0
      - 256
    preload: true
    dataset_csv: /vol/ideadata/ce90tate/data/mimic/cxr-record-list-impressions-no_p19.csv

  test:
    dataset: chestxraymimicbbox
    base_dir: /vol/ideadata/ce90tate/data/mimic
    split: mscxr
    preload: true
    save_original_images: true

sample:
  ddim_steps: 75
  iou_batch_size: 8
  n_synth_samples_per_class: 625
  seed: 4200
  latent_C: 4
  latent_H: 64
  latent_W: 64
