latent_attention_masks: False
phrase_grounding_mode: True
root: /vol/ideadata/ce90tate/
work_dir: /vol/ideadata/ce90tate/chest-distillation
data_dir: /vol/ideadata/ce90tate/data/mscoco

dataloading:
  batch_size: 8
  num_workers: 0

datasets:
  C: 4
  H: 512
  W: 512
  f: 8
  train:
    dataset: mscoco
    base_dir: /vol/ideadata/ce90tate/data/mscoco
    split: train
    preload: true

  val:
    dataset: mscoco
    base_dir: /vol/ideadata/ce90tate/data/mscoco
    split: val
    limit_dataset:
      - 0
      - 64
    preload: true

  test_sample:
    dataset: mscoco
    base_dir: /vol/ideadata/ce90tate/data/mscoco
    split: test
    preload: true


