#!/bin/bash
accelerate launch $WORK/cxr_phrase_grounding/train_radbert_lora.py \
--pretrained_model_name_or_path=$WORK/cxr_phrase_grounding/components \
--gradient_accumulation_steps=4 \
--max_train_steps=30001 \
--learning_rate=5e-05 \
--max_grad_norm=1 \
--lr_scheduler="cosine" \
--lr_warmup_steps=0 \
--output_dir=$WORK/cxr_phrase_grounding/finetune/lora/radbert \
--report_to=wandb \
--checkpointing_steps=1000 \
--validation_epochs=100 \
--seed=1337 \
--config=config_msxcr_hpc.yml \
--validation_prompt="An image of a chest xray" \
--cache_dir=$WORK/cxr_phrase_grounding/.cache \
--generation_validation_epochs=1000 \
--train_batch_size=64 \
--resume_from_checkpoint=latest