#!/bin/bash
accelerate launch /vol/ideadata/ce90tate/cxr_phrase_grounding/training/train_radbert.py \
--pretrained_model_name_or_path=/vol/ideadata/ce90tate/cxr_phrase_grounding/components \
--gradient_accumulation_steps=1 \
--max_train_steps=15001 \
--learning_rate=5e-05 \
--max_grad_norm=1 \
--lr_scheduler="cosine" \
--lr_warmup_steps=0 \
--output_dir=/vol/ideadata/ce90tate/cxr_phrase_grounding/finetune/normal/radbert \
--checkpointing_steps=50 \
--validation_epochs=50 \
--seed=1337 \
--config=/vol/ideadata/ce90tate/cxr_phrase_grounding/configs/config_msxcr.yml \
--validation_prompt="An image of a chest xray" \
--cache_dir=/vol/ideadata/ce90tate/cxr_phrase_grounding/.cache \
--generation_validation_epochs=50 \
--train_batch_size=16 \
--resume_from_checkpoint=latest \
--use_ema